#!/usr/bin/env bash
# This script pings an IP address passed as an argument

if [[ $# -eq 0 ]]; then
    # Use basename to remove any directory paths from $BASH_SOURCE
    echo "Usage: $(basename "$BASH_SOURCE") {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"
