#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely with a delay of 2 seconds between each iteration
# It also prints "I am invincible!!!" when it receives a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
