#!/usr/bin/env bash
# This script prints "Best School" 10 times using a while loop, but for the 9th iteration, it also prints "Hi"

counter=1
while [[ $counter -le 10 ]]
do
   echo "Best School"
   if [[ $counter -eq 9 ]]
   then
      echo "Hi"
   fi
   ((counter++))
done
